name: Build Vue
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add write workflow permissions
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dir list
        run: ls -l ./

      - name: npm install
        run: npm install

      - name: dir list
        run: ls -l ./

      - name: deploy
        run: |
              cd dist
              ls -l ./
              git config --global user.email "lishnih@gmail.com"
              git config --global user.name "Stan Ovchinnikov"
              git init
              git add .
              git commit -m 'Create gh-pages'
              git push -f https://ndtfy:${{ secrets.GITHUB_TOKEN }}@github.com/ndtfy/test-gh-pages.git master:gh-pages
